# -*- coding: utf-8 -*-
"""MOVIE-recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V6gWOvYWRO3kmlxt_rzNYM1zNqCFwkH_
"""

print("hello world")

x=5+7
y=x-5
z=x>y
print(x)
print(y)
print(z)

x=['azeem','ansiya','bossified','aadhil']
x.append('fazil')
print(x)

x=['azeem','ansiya','bossified','aadhil']
x.pop(1)
print(x)

x=("azeem","amana","sabitha")
x.append("orange")
print(x)

for x in range(1,51):
 print(x)

x=1

while x < 51:
  print(x)
  x=x+1

x=5+5
y=2+5
z=5
if x<z:
  print("z is greater than  x")
elif x==z:
    print("x and z are equal")
else:
  print("x is greater than z")

def x(name):
  print("hi"+name)
x("azeem")

def my_function(name="friend"):
  print("hi ",name)
my_function("azeem")
my_function("fazil")
my_function()
my_function("shadhi")

def my_function(friend,name):
  print("i have a friend",friend)
  print("my friend"'s name is",name)


my_function("azeem","abdul azeem")

def my_function(animal,name):
  print("i have a",animal)
  print("my",animal+"'s name is",name)


my_function("buddy","dog")

def my_function(ranks):
  for rank in ranks:
    print(rank)

my_function(["a+","b+","c+","d+","e+"

def my_function(school):
  for key in school:
    print(key+)

def my_function(x,y):
  return x*y

calc=my_function(8,2)
print(calc)

def sum_list(numbers):
  total=0
  for num in numbers:
    total+=num
  return total
my_list=[8,9,6,9,7]
calc=sum_list(my_list)
print(calc)

class myclass:
  x=5
p1=myclass()
p2=myclass()
p3=myclass()
p4=myclass
print(p1.x)
print(p2.x)
print(p3.x)
del p3

class person:
  def __init__(self,name,age=35):
    self.name=name
    self.age=age
p1=person("ansiya",)
print(p1.name)
print(p1.age)

from typing import AsyncGenerator
class person:
  def __init__(self,name,age):
    self.name=name
    self.age=AsyncGenerator
  def greet(self):
    print("hello, my name is "+self.name)

    p1=person("emil",25)
    p1.greet()

def factorial(n):
  if n == 0 or n ==1:
    return 1
  else:
    return n * factorial(n-1)
print(factorial(5))

from types import ModuleType
class car:
  def __init__(self,brand,model):
    self.brand = brand
    self.model = model
car1=car("ford","mustang")
car2=car("toyota","camry")
car3=car("honda","civic")
print(car2.brand)
print(car2.model)

class person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def get_info(self):
    return f"{self.name}, {self.age} years old"

p1 = person("emil", 25)
print(p1.get_info())

class playlist:
  def __init__(self, name):
    self.name = name
    self.songs = []

  def add_song(self, song):
    self.songs.append(song)
    print(f"added: {song}")

  def remove_song(self, song):
    if song in self.songs:
      self.songs.remove(song)
      print(f"removed {song}")

  def show_songs(self):
    print(f"playlist '{self.name}':")
    for song in self.songs:
      print(f"-{song}")

playlist1 = playlist("fav")
playlist1.add_song("gta")
playlist1.add_song("song2")
playlist1.add_song("song3")

from typing import Self
class bankaccount:
  def __init__(self,name,balance):
    self.name=name
    self.balance=balance
  def deposite(self,amount):
    self.balance+=amount
    print("deposited:",amount)
  def withdraw(self,amount):
    if amount > self.balance:
      print("insufficient balance")
    else:
      self.balance-=amount
      print("withdrawn:",amount)
  def show_balance(self):
    print("withdrawn:",amount)
  def show_balance(self):
    print(self.name, "balance:",self.balance)

from typing import Self
class bankaccount:
  def __init__(self,name,balance):
    self.name=name
    self.balance=balance
  def deposite(self,amount):
    self.balance+=amount
    print("deposited:",amount)
  def withdraw(self,amount):
    if amount > self.balance:
      print("insufficient balance")
    else:
      self.balance-=amount
      print("withdrawn:",amount)
  def show_balance(self):
    print("withdrawn:",amount)
  def show_balance(self):
    print(self.name, "balance:",self.balance)

from typing import Self
class bankaccount:
  def __init__(self,name,balance):
    self.name=name
    self.balance=balance
  def deposite(self,amount):
    self.balance+=amount
    print("deposited:",amount)
  def withdraw(self,amount):
    if amount > self.balance:
      print("insufficient balance")
    else:
      self.balance-=amount
      print("withdrawn:",amount)
  def show_balance(self):
    print("withdrawn:",amount)
  def show_balance(self):
    print(self.name, "balance:",self.balance)


  acc1 = bankaccount("akash",1000)

  acc1.deposit(500)
  acc1.withdrw(300)
  acc1.show_balance()

class Student(Person):
  def __init__(self, fname, lname):
    super().__init__(fname, lname)
    self.graduationyear = 2019

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  pass

x = Person("John", "Doe")
x.printname()

class Animal:
  def __init__(self, name):
    self.name = name

  def speak(self):
    print(self.name)

class Dog(Animal):
  pass

d1 = Dog("Rex")
d1.speak()

class Car:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Drive!")

class Boat:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Sail!")

class Plane:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Fly!")

car1 = Car("Ford", "Mustang")       #Create a Car object
boat1 = Boat("Ibiza", "Touring 20") #Create a Boat object
plane1 = Plane("Boeing", "747")     #Create a Plane object

for x in (car1, boat1, plane1):
  x.move()

# Create the Cat class
class Cat:
  def sound(self):
    print("Meow")

# Create the Fox class
class Fox:
  def sound(self):
    print("Wa-pa-pa-pa-pa-pow!")

# Create objects and loop
c1 = Cat()
f1 = Fox()

for animal in (c1, f1):
  animal.sound()

class Person:
  def __init__(self, name, age):
    self.name = name
    self.__age = age

  def get_age(self):
    return self.__age

p1 = Person("Tobias", 25)
print(p1.get_age())

class Person:
  def __init__(self, name, age):
    self.name = name
    self.__age = age

  def get_age(self):
    return self.__age

  def set_age(self, age):
    if age > 0:
      self.__age = age
    else:
      print("Age must be positive")

p1 = Person("Tobias", 25)
print(p1.get_age())

p1.set_age(26)
print(p1.get_age())

# Create the ScoreBoard class
class ScoreBoard:
  def __init__(self, score):
    self.__score = score

  def get_score(self):
    return self.__score

# Create an object
s1 = ScoreBoard(0)

# Print the score
print(s1.get_score())

class Outer:
  def __init__(self):
    self.name = "Outer"

  class Inner:
    def __init__(self):
      self.name = "Inner"

    def display(self):
      print("Hello from inner class")

outer = Outer()
inner = outer.Inner()
inner.display()

def linearsearch(arr, targetVal):
  for i in range(len(arr)):
    if arr[i] == targetVal:
      return i
  return -1
mylist=[3,2,5,6,3,3,1]
x=9

result= linearsearch(mylist,x)
if result != -1:
  print("element found at index",result)
else:
  print("element not found")

def binarysearch(arr, targetVal):
  low = 0
  high = len(arr) - 1


  while low <= high:
    mid = (low + high) // 2
    if arr[mid] == targetVal:
      return mid
    elif arr[mid] < targetVal:
      low = mid + 1
    else:
      high = mid - 1

mylist=[64,34,25,12,22,11,90,5]


n=len(mylist)
for i in range(n):
  for j in range(0,n-i-1):
    if mylist[j]>mylist[j+1]:
      mylist[j],mylist[j+1]=mylist[j+1],mylist[j]
print(mylist)

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression


y=np.array([
    [3,4],
    [6,8],
    [4,9],
    [7,9],
])

x=np.array([1,0,1,0])

model=LogisticRegression()
model.fit(y,x)


y_min, y_max = y[:, 0].min() - 1, y[:, 0].max() + 1
x_min, x_max = y[:, 1].min() - 1, y[:, 1].max() + 1
yy,xx=np.meshgrid(np.arange(y_min,y_max,0.1),np.arange(x_min,x_max,0.1))
z=model.predict(np.c_[yy.ravel(),xx.ravel()])
z=z.reshape(yy.shape)
plt.contourf(yy,xx,z,alpha=0.4,cmap=plt.cm.Paired)
plt.scatter(y[:,0],y[:,1],c=x,s=70,edgecolors='k',cmap=plt.cm.Paired)

plt.xlabel("part-1")
plt.ylabel("part-2")
plt.title("boundary")
plt.show()

import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier, plot_tree

# Dataset
# [Age, Monthly Income in thousands]
X = [
    [18, 15],
    [20, 18],
    [22, 20],
    [25, 25],
    [28, 30],
    [32, 40],
    [35, 50],
    [40, 60]
]

# 0 = Will Not Buy
# 1 = Will Buy
y = [0, 0, 0, 1, 1, 1, 1, 1]

# Create model
model = DecisionTreeClassifier(max_depth=3)

# Train model
model.fit(X, y)

# Plot tree
plt.figure(figsize=(12, 7))

plot_tree(
    model,
    feature_names=["Age", "Income"],
    class_names=["No Buy", "Buy"],
    filled=True,
    rounded=True,
    fontsize=11
)

plt.title("Laptop Purchase Prediction")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB


#dataset
#[number of links,number of special charecters]
x=np.array([
    [1, 1],
    [2, 1],
    [1, 2],
    [2, 2],
    [7, 8],
    [8, 9],
    [9, 8],
    [8, 7]

])
y = np.array([0, 0, 0, 0, 1, 1, 1, 1])

import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# Create dataset
X, y = make_blobs(
    n_samples=200,
    centers=2,
    random_state=42,
    cluster_std=1.5
)

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = SVC(kernel='linear')

model.fit(X_train, y_train)

# Accuracy
accuracy = model.score(X_test, y_test)
print("Accuracy:", accuracy)

# Plot data
plt.scatter(X[:, 0], X[:, 1], c=y, cmap='coolwarm')
plt.title("SVM Classification")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# Create dataset
X, y = make_blobs(
    n_samples=200,
    centers=2,
    random_state=42,
    cluster_std=1.5
)

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# Train SVM model
model = SVC(kernel='linear')
model.fit(X_train, y_train)

# Plot figure
plt.figure(figsize=(8, 6))

# Scatter plot
plt.scatter(
    X[:, 0],
    X[:, 1],
    c=y,
    cmap='coolwarm'
)

# Get current axis
ax = plt.gca()

# Get axis limits
xlim = ax.get_xlim()
ylim = ax.get_ylim()

# Create grid
xx = np.linspace(xlim[0], xlim[1], 100)
yy = np.linspace(ylim[0], ylim[1], 100)

YY, XX = np.meshgrid(yy, xx)

# Flatten grid points
xy = np.vstack([XX.ravel(), YY.ravel()]).T

# Decision function
Z = model.decision_function(xy).reshape(XX.shape)

# Decision boundary and margins
plt.contour(
    XX,
    YY,
    Z,
    colors='black',
    levels=[-1, 0, 1],
    alpha=0.7,
    linestyles=['--', '-', '--']
)

# Highlight support vectors
plt.scatter(
    model.support_vectors_[:, 0],
    model.support_vectors_[:, 1],
    s=100,
    linewidth=1,
    facecolors='none',
    edgecolors='k'
)

# Labels and title
plt.title("SVM Decision Boundary")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")

plt.show()

import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import make_circles
from sklearn.svm import SVC

# Generate synthetic circular data
X, y = make_circles(
    n_samples=300,
    noise=0.1,
    factor=0.2,
    random_state=42
)

# Initialize and fit the Support Vector Classifier
# Note: Your title says RBF, but the model code shows kernel="linear"
model = SVC(kernel="linear")
model.fit(X, y)

# Create a mesh grid for plotting decision boundaries
x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1

xx, yy = np.meshgrid(
    np.linspace(x_min, x_max, 500),
    np.linspace(y_min, y_max, 500)
)

# Predict across the mesh grid
z = model.predict(np.c_[xx.ravel(), yy.ravel()])
z = z.reshape(xx.shape)

# Visualization
plt.figure(figsize=(8, 6))

# Plot decision boundary
plt.contourf(xx, yy, z, alpha=0.3)

# Plot the data points
plt.scatter(
    X[:, 0],
    X[:, 1],
    c=y,
    cmap='coolwarm',
    edgecolors='black'
)

# Highlight the Support Vectors
plt.scatter(
    model.support_vectors_[:, 0],
    model.support_vectors_[:, 1],
    s=120,
    facecolors='none',
    edgecolors='black',
    linewidth=2,
    label="Support Vectors"
)

plt.title("SVM with RBF kernel")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.neighbors import KNeighborsClassifier

x,y=make_blobs(
    n_samples=200,
    centers=2,
    random_state=42,
    cluster_std=1.5
)

model=KNeighborsClassifier(n_neighbors=5)
model.fit(x,y)

x_min,x_max=x[:,0].min()-1,x[:,0].max()+1
y_min,y_max=x[:,1].min()-1,x[:,1].max()+1

xx,yy=np.meshgrid(np.linspace(x_min,x_max,0.1),np.linspace(y_min,y_max,0.1))
    np.arange(y_min,y_max,0.1)
    np,arange(x_min,x_max,0.1)

    z=model.predict(np.c_[xx.ravel(),yy.ravel()])
    z=z.reshape(xx.shape)

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.neighbors import KNeighborsClassifier

x,y=make_blobs(
    n_samples=200,
    centers=2,
    random_state=42,
    cluster_std=1.5
)

model=KNeighborsClassifier(n_neighbors=5)
model.fit(x,y)

x_min,x_max=x[:,0].min()-1,x[:,0].max()+1
y_min,y_max=x[:,1].min()-1,x[:,1].max()+1

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

print("Shape of x_train:", x_train.shape)
print("Shape of x_test:", x_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

from sklearn.neighbors import KNeighborsClassifier

# Re-initialize and train the KNN model (as x and y might have been overwritten)
model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(x_train, y_train)

# Calculate the accuracy score on the test set
accuracy_knn = model_knn.score(x_test, y_test)
print(f"Accuracy of KNN model on the test set: {accuracy_knn:.4f}")

"""### Part 1: Initial Setup and Data Loading

*   **Python Basics**: Review fundamental Python syntax, data structures (lists, tuples, dictionaries), and control flow (loops, conditionals).
*   **NumPy**: Familiarize yourself with array creation, manipulation, and vectorized operations for efficient numerical computation.
*   **Pandas**: Understand DataFrame and Series objects, data loading (CSV, Excel), basic data cleaning, and manipulation.
*   **Scikit-learn (Basic)**: Get acquainted with the basic workflow of `fit`, `predict`, and `score` methods for machine learning models.
*   **Matplotlib**: Learn to create various types of plots for data visualization.

### Part 2: Model Building and Evaluation

*   **Supervised Learning Algorithms**: Deep dive into algorithms like Linear Regression, Logistic Regression, Decision Trees, K-Nearest Neighbors (KNN), and Support Vector Machines (SVMs). Focus on their underlying principles, strengths, and weaknesses.
*   **Model Evaluation Metrics**: Learn about appropriate metrics for classification (accuracy, precision, recall, F1-score, ROC AUC) and regression (MAE, MSE, R-squared).
*   **Data Splitting**: Understand the importance of train-test splits and cross-validation for robust model evaluation.
*   **Matplotlib/Seaborn**: Enhance your data visualization skills to effectively present model results and data insights.
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.neighbors import KNeighborsClassifier

x,y=make_blobs(
    n_samples=200,
    centers=2,
    random_state=42,
    cluster_std=1.5
)

model=KNeighborsClassifier(n_neighbors=5)
model.fit(x,y)

x_min,x_max=x[:,0].min()-1,x[:,0].max()+1
y_min,y_max=x[:,1].min()-1,x[:,1].max()+1

# Corrected meshgrid creation using np.arange for step size
# We'll use a step of 0.02 for smoother boundaries
xx,yy=np.meshgrid(np.arange(x_min,x_max,0.02),
                     np.arange(y_min,y_max,0.02))

# Predict across the meshgrid
z=model.predict(np.c_[xx.ravel(),yy.ravel()])
z=z.reshape(xx.shape)

plt.figure(figsize=(8,6))
# Plot the decision boundary
plt.contourf(xx,yy,z,alpha=0.4,cmap='coolwarm')
# Plot the original data points
plt.scatter(x[:,0],x[:,1],c=y,cmap='coolwarm',edgecolors='black')
plt.title("K-Nearest Neighbors Decision Boundary")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_classification
from sklearn.neighbors import KNeighborsClassifier

# Create dataset
X, y = make_classification(
    n_samples=150,
    n_features=2,
    n_redundant=0,
    n_clusters_per_class=1,
    random_state=42
)

# Train KNN
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X, y)

# New point
new_point = np.array([[8, 2]])

# Predict new point
prediction = model.predict(new_point)

# Plot data
plt.figure(figsize=(8, 6))

plt.scatter(
    X[:, 0],
    X[:, 1],
    c=y,
    cmap='coolwarm',
    edgecolors='black'
    s=250
    marker='*',
    label=f'Class {prediction[0]}')

import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression


x=np.array([1,2,3,4,5,6]).reshape(-1,1)
y=np.array([3,5,7,9,11,13])


model = LinearRegression()
model.fit(x, y)
y_pred=model.predict(x)

plt.figure(figsize=(8,6))
plt.scatter(x,y,color='blue',label='actual data')
plt.plot(x,y_pred,color='teal',label='predicted data')
plt.title('simple Linear Regression')
plt.xlabel('x fazil')
plt.ylabel('y shadhi')
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Create dataset
X, y = make_regression(
    n_samples=100,
    n_features=1,
    noise=15,
    random_state=42
)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model=LinearRegression()

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

y_pred=model.predict(X_test)

plt.figure(figsize=(8,6))
plt.scatter(X_test,y_test,color='blue',label='actual data')
plt.plot(X_test,y_pred,color='teal',label='predicted data')
plt.title('simple Linear Regression')
plt.xlabel('feature')
plt.ylabel('target')
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_classification
from sklearn.ensemble import GradientBoostingClassifier # Changed from sklearn.linear_model to sklearn.ensemble

x,y=make_classification(

                        n_samples=100,
                        n_features=2,
                        n_redundant=0,
                        n_clusters_per_class=1,
                        random_state=42
)
model=GradientBoostingClassifier() # Removed indent and fixed typo
model.fit(x,y)

x_min,x_max=x[:,0].min()-1,x[:,0].max()+1
y_min,y_max=x[:,1].min()-1,x[:,1].max()+1 # Corrected y[:,1] to x[:,1]

xx,yy=np.meshgrid(np.arange(x_min,x_max,0.02),
                     np.arange(y_min,y_max,0.02))

z=model.predict(np.c_[xx.ravel(),yy.ravel()])
z=z.reshape(xx.shape)

# Removed the redundant 'plt' line

plt.figure(figsize=(8,6))
plt.contourf(xx,yy,z,alpha=0.4,cmap='coolwarm')
plt.scatter(x[:,0],x[:,1],c=y,cmap='coolwarm',edgecolors='black') # Corrected x[:,3] to x[:,1]
plt.title("Gradient Boosting Classification") # Added a title
plt.xlabel("Feature 1") # Added axis labels
plt.ylabel("Feature 2")
plt.show()

import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier, plot_tree

# Dataset
# [Age, Monthly Income in thousands]
X = [
    [18, 15],
    [20, 18],
    [22, 20],
    [25, 25],
    [28, 30],
    [32, 40],
    [35, 50],
    [40, 60]
]

# 0 = Will Not Buy
# 1 = Will Buy
y = [0, 0, 0, 1, 1, 1, 1, 1]

# Create model
model = DecisionTreeClassifier(max_depth=3)

# Train model
model.fit(X, y)

# Plot tree
plt.figure(figsize=(12, 7))

plot_tree(
    model,
    feature_names=["Age", "Income"],
    class_names=["No Buy", "Buy"],
    filled=True,
    rounded=True,
    fontsize=11
)

plt.title("Laptop Purchase Prediction")
plt.show()

import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.datasets import make_classification

X_new, y_new = make_classification(
    n_samples=100,
    n_features=2,
    n_redundant=0,
    n_clusters_per_class=1,
    random_state=123
)

model_new = DecisionTreeClassifier(max_depth=10, random_state=42)
model_new.fit(X_new, y_new)

plt.figure(figsize=(20, 10))
plot_tree(
    model_new,
    feature_names=["Feature 1", "Feature 2"],
    class_names=["Class 0", "Class 1"],
    filled=True,
    rounded=True,
    fontsize=8
)
plt.title("Random Decision Tree with max_depth=10")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=10, n_features=2, n_redundant=0,
                           n_clusters_per_class=1, random_state=42)
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X, y)

x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.02),
                     np.arange(y_min, y_max, 0.02))

Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
Z = Z.reshape(xx.shape)
plt.figure(figsize=(8, 6))
plt.contourf(xx, yy, Z, alpha=0.3, cmap='coolwarm')
plt.scatter(X[:, 0], X[:, 1], c=y, cmap='coolwarm', edgecolors='black', s=100)
plt.title("Random Forest Classification (10 Samples)")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.show()
print(f"Accuracy on 10 samples: {model.score(X, y)}")

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
y_true = [1, 0, 1, 1, 0, 0, 1, 0]
y_pred = [1, 0, 1, 0, 0, 1, 1, 0] # Corrected to match y_true length
cm=confusion_matrix(y_true,y_pred)
disp=ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=['negative','positive'])
disp.plot(cmap=plt.cm.Blues)
plt.title("2x2 Confusion Matrix")
plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import (
    confusion_matrix, ConfusionMatrixDisplay,
    accuracy_score, precision_score, recall_score, f1_score
)
y_true = [0,1,2,2,0,1,2,0]
y_pred = [0,1,2,1,0,0,2,0] # Corrected to match y_true length
cm=confusion_matrix(y_true,y_pred)
disp=ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=['class 0','class 1','class 2'])
disp.plot(cmap=plt.cm.Blues)
plt.title("3x3 Confusion Matrix")
plt.show()
accuracy=accuracy_score(y_true,y_pred)
precision=precision_score(y_true,y_pred, average='weighted')
recall=recall_score(y_true,y_pred, average='weighted')
f1=f1_score(y_true,y_pred, average='weighted')
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

import matplotlib.pyplot as plt
from sklearn.metrics import (
    confusion_matrix, ConfusionMatrixDisplay,
    accuracy_score, precision_score, recall_score, f1_score
)
y_true = [0,1,2,2,0,1,2,0]
y_pred = [0,1,2,1,0,0,2,0] # Corrected to match y_true length
cm=confusion_matrix(y_true,y_pred)
disp=ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=['class 0','class 1','class 2'])
disp.plot(cmap=plt.cm.Blues)
plt.title("2x2 Confusion Matrix")
plt.show()
accuracy=accuracy_score(y_true,y_pred)
precision=precision_score(y_true,y_pred, average='weighted')
recall=recall_score(y_true,y_pred, average='weighted')
f1=f1_score(y_true,y_pred, average='weighted')
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import (
    confusion_matrix, ConfusionMatrixDisplay,
    accuracy_score, precision_score, recall_score, f1_score
)

# 3x3 Confusion Matrix and metrics
y_true_multi = [0,1,2,2,0,1,2,0]
y_pred_multi = [0,1,2,1,0,0,2,0]
cm_multi = confusion_matrix(y_true_multi,y_pred_multi)
disp_multi = ConfusionMatrixDisplay(confusion_matrix=cm_multi,display_labels=['class 0','class 1','class 2'])
disp_multi.plot(cmap=plt.cm.Blues)
plt.title("3x3 Confusion Matrix")
plt.show()

accuracy = accuracy_score(y_true_multi,y_pred_multi)
precision = precision_score(y_true_multi,y_pred_multi, average='weighted')
recall = recall_score(y_true_multi,y_pred_multi, average='weighted')
f1 = f1_score(y_true_multi,y_pred_multi, average='weighted')
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

from sklearn.metrics import classification_report

# Generate and print the classification report
report = classification_report(y_true_multi, y_pred_multi, target_names=['class 0', 'class 1', 'class 2'])
print("Classification Report:\n", report)

import matplotlib.pyplot as plt
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

# Actual and Predicted Values
y_true = [10, 20, 30, 40, 50]
y_pred = [12, 18, 29, 41, 52]

# Calculate Metrics
mae = mean_absolute_error(y_true, y_pred)
mse = mean_squared_error(y_true, y_pred)

# print metrics
print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
# RMSE and R2 Score
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
r2 = r2_score(y_true, y_pred)

# Print metrics
print(f"RMSE: {rmse:.2f}")
print(f"R2 Score: {r2:.2f}")

# Plot Regression Metrics
methods = ['MAE', 'MSE', 'RMSE', 'R2 Score']
values_for_plot = [mae, mse, rmse, r2]

# Plot bar graph
plt.figure(figsize=(7,5))
plt.bar(methods, values_for_plot, color=['skyblue', 'lightcoral', 'lightgreen', 'gold'])

# Labels and title
plt.title("Regression Metrics")
plt.xlabel("Metrics")
plt.ylabel("Values")

plt.show()

import os
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import requests # For downloading the file
import zipfile # For extracting zip files
import shutil # For cleaning up directories

# Define the filename
csv_filename = "movies.csv"

# Check if the file exists, if not, download it
if not os.path.exists(csv_filename):
    print(f"'{csv_filename}' not found. Attempting to download a sample dataset...")
    try:
        # URL for the small MovieLens dataset zip file
        zip_url = "http://files.grouplens.org/datasets/movielens/ml-latest-small.zip"
        local_zip_path = "ml-latest-small.zip"

        # Download the zip file
        r = requests.get(zip_url, stream=True)
        r.raise_for_status() # Raise an exception for bad status codes
        with open(local_zip_path, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)
        print("Downloaded ml-latest-small.zip successfully.")

        # Extract movies.csv from the zip file
        with zipfile.ZipFile(local_zip_path, 'r') as zip_ref:
            # The movies.csv is typically inside a folder like ml-latest-small/
            zip_ref.extract('ml-latest-small/movies.csv', path='./')

        # Move movies.csv to the current directory and clean up
        os.rename('ml-latest-small/movies.csv', csv_filename)
        shutil.rmtree('ml-latest-small') # Clean up extracted directory
        os.remove(local_zip_path) # Clean up zip file

        print(f"Successfully downloaded and extracted '{csv_filename}'.")

    except Exception as e:
        print(f"Could not download or extract '{csv_filename}'. Please ensure you have the file in the correct directory. Error: {e}")
        # Fallback: Create a dummy file if download fails to allow code to run
        dummy_data = {'movieId': [1, 2, 3], 'title': ['Toy Story (1995)', 'Jumanji (1995)', 'Waiting to Exhale (1995)'], 'genres': ['Animation|Children|Comedy', 'Adventure|Children|Fantasy', 'Comedy|Drama']}
        movies = pd.DataFrame(dummy_data)
        movies.to_csv(csv_filename, index=False)
        print(f"Created a dummy '{csv_filename}' for demonstration purposes.")

# Load dataset
movies = pd.read_csv(csv_filename)

# Display first 5 rows
print(movies.head())

# Fill missing values (important if 'genres' might be missing)
movies.fillna('', inplace=True)

# Select features
features = ['genres']

# Combine features into one column
def combine_features(row):
    return row['genres']

movies["combined_features"] = movies.apply(combine_features, axis=1)

# Convert text to matrix
cv = CountVectorizer()

count_matrix = cv.fit_transform(movies["combined_features"])

# Calculate cosine similarity
cosine_sim = cosine_similarity(count_matrix)

# Movie recommendation function
def recommend_movie(movie_name):
    # Check if movie_name exists in the dataset
    if movie_name not in movies['title'].values:
        print(f"Error: Movie '{movie_name}' not found in the dataset. Please try a different movie title.")
        return

    # Find movie index
    movie_index = movies[movies.title == movie_name].index[0]

    # Get similarity scores
    similarity_scores = list(enumerate(cosine_sim[movie_index]))

    # Sort movies by similarity score in descending order
    sorted_similar_movies = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

    # Print recommendations (excluding the movie itself)
    print(f"\nTop Recommended Movies for '{movie_name}':\n")

    recommendation_count = 0
    for movie_id, score in sorted_similar_movies:
        if movie_id == movie_index: # Skip the movie itself
            continue
        if recommendation_count >= 10: # Limit to top 10 recommendations
            break

        title = movies.iloc[movie_id]["title"]
        print(f"{recommendation_count + 1}. {title}")
        recommendation_count += 1

    if recommendation_count == 0:
        print("No similar movies found or the dataset is too small for recommendations.")

# Example
recommend_movie("Toy Story (1995)")

import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

# Extract all genres and count their occurrences
all_genres = []
for index, row in movies.iterrows():
    genres = row['genres'].split('|')
    for genre in genres:
        if genre: # Ensure genre is not an empty string
            all_genres.append(genre)

genre_counts = Counter(all_genres)

# Convert to DataFrame for easier plotting
genre_df = pd.DataFrame(genre_counts.items(), columns=['Genre', 'Count']).sort_values(by='Count', ascending=False)

# Plot the distribution of genres
plt.figure(figsize=(12, 8))
sns.barplot(x='Count', y='Genre', data=genre_df.head(20), palette='viridis')
plt.title('Top 20 Movie Genre Distribution')
plt.xlabel('Number of Movies')
plt.ylabel('Genre')
plt.tight_layout()
plt.show()

search_term = "gene"
matching_movies = movies[movies['title'].str.contains(search_term, case=False, na=False)]

if not matching_movies.empty:
    print(f"Movies containing '{search_term}' in their title:")
    for index, row in matching_movies.head(20).iterrows(): # Display up to 20 matches
        print(f"- {row['title']}")
    if len(matching_movies) > 20:
        print(f"... and {len(matching_movies) - 20} more. Refine your search if needed.")
else:
    print(f"No movies found containing '{search_term}' in their title.")

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Movie data
data = {
    'movie': [
        'Avatar', 'Titanic', 'Avengers', 'Batman',
        'Spider-Man', 'Iron Man', 'Joker', 'Frozen',
        'Inception', 'Interstellar', 'The Dark Knight',
        'Doctor Strange', 'Thor', 'Black Panther',
        'Finding Nemo', 'Toy Story', 'Cars',
        'Harry Potter', 'Lord of the Rings',
        'The Conjuring', 'Annabelle', 'It',
        'Fast and Furious', 'John Wick',
        'Deadpool', 'Venom', 'Shrek',
        'Kung Fu Panda', 'Minions', 'Moana'
    ],

    'genre': [
        'sci-fi action adventure',
        'romance drama',
        'action superhero',
        'dark action hero',
        'action superhero adventure',
        'technology action superhero',
        'psychological crime drama',
        'animation fantasy family',
        'mind-bending sci-fi thriller',
        'space sci-fi drama',
        'crime dark action',
        'magic superhero fantasy',
        'mythology action fantasy',
        'africa superhero action',
        'animation family adventure',
        'animation comedy family',
        'animation racing comedy',
        'magic fantasy adventure',
        'fantasy war adventure',
        'horror supernatural',
        'horror doll supernatural',
        'horror thriller clown',
        'racing action crime',
        'action assassin thriller',
        'comedy action superhero',
        'dark superhero sci-fi',
        'animation comedy fantasy',
        'animation martial-arts comedy',
        'animation comedy family',
        'animation ocean adventure'
    ]
}
movies = pd.DataFrame(data)

# Convert genre text to numbers
tfidf = TfidfVectorizer()
vectors = tfidf.fit_transform(movies['genre'])

# Similarity
similarity = cosine_similarity(vectors)

# User input
genre = input("Enter genre: ")

# Convert input
user_vector = tfidf.transform([genre])

# Compare with movies
scores = cosine_similarity(user_vector, vectors)

# Best movie
best_index = scores.argmax()

print("Recommended Movie:", movies.iloc[best_index]['movie'])

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Movie data
data = {
    'movie': [
        'Avatar', 'Titanic', 'Avengers', 'Batman',
        'Spider-Man', 'Iron Man', 'Joker', 'Frozen',
        'Inception', 'Interstellar', 'The Dark Knight',
        'Doctor Strange', 'Thor', 'Black Panther',
        'Finding Nemo', 'Toy Story', 'Cars',
        'Harry Potter', 'Lord of the Rings',
        'The Conjuring', 'Annabelle', 'It',
        'Fast and Furious', 'John Wick',
        'Deadpool', 'Venom', 'Shrek',
        'Kung Fu Panda', 'Minions', 'Moana'
    ],

    'genre': [
        'sci-fi action adventure',
        'romance drama',
        'action superhero',
        'dark action hero',
        'action superhero adventure',
        'technology action superhero',
        'psychological crime drama',
        'animation fantasy family',
        'mind-bending sci-fi thriller',
        'space sci-fi drama',
        'crime dark action',
        'magic superhero fantasy',
        'mythology action fantasy',
        'africa superhero action',
        'animation family adventure',
        'animation comedy family',
        'animation racing comedy',
        'magic fantasy adventure',
        'fantasy war adventure',
        'horror supernatural',
        'horror doll supernatural',
        'horror thriller clown',
        'racing action crime',
        'action assassin thriller',
        'comedy action superhero',
        'dark superhero sci-fi',
        'animation comedy fantasy',
        'animation martial-arts comedy',
        'animation comedy family',
        'animation ocean adventure'
    ]
}
movies = pd.DataFrame(data)

# Convert genre text to numbers
tfidf = TfidfVectorizer()
vectors = tfidf.fit_transform(movies['genre'])

# Similarity
similarity = cosine_similarity(vectors)

print("Choose a genre number:")
print("1. action superhero")
print("2. sci-fi adventure")
print("3. horror supernatural")
print("4. animation comedy")
print("5. magic fantasy")
print("6. romance drama")
print("7. action thriller")

# User choice
choice = input("\nEnter number: ")

# Convert number to genre
genre_dict = {
    "1": "action superhero",
    "2": "sci-fi adventure",
    "3": "horror supernatural",
    "4": "animation comedy",
    "5": "magic fantasy",
    "6": "romance drama",
    "7": "action thriller"
}

genre = genre_dict.get(choice, "")

# Check valid input
if genre == "":
    print("Invalid choice")
else:
    # Convert input
    user_vector = tfidf.transform([genre])

    # Compare with movies
    scores = cosine_similarity(user_vector, vectors)

    # Best movie
    best_index = scores.argmax()

    print("Recommended Movie:", movies.iloc[best_index]['movie'])
# Convert input
user_vector = tfidf.transform([genre])

# Compare with movies
scores = cosine_similarity(user_vector, vectors)

# Best movie
best_index = scores.argmax()

print("Recommended Movie:", movies.iloc[best_index]['movie'])